'use strict';
// SHAZ Finance: source orders stay in orders.json; this file holds only financial overlays.
const crypto=require('crypto');
const DEFAULT=()=>({v:1,purchases:[],allocations:[],expenses:[],refunds:[],tariffs:[],personalizationRates:[],costs:{},vatAdjustments:[],audit:[],operations:[]});
const cents=value=>{const n=Number(value);if(!Number.isFinite(n))throw Error('Tutar geçerli bir sayı olmalı.');return Math.round((n+Number.EPSILON)*100)};
const money=c=>Math.round(c)/100;
const nonnegative=(v,label='Tutar')=>{const x=cents(v);if(x<0||x>1e12)throw Error(label+' sıfır veya pozitif olmalı.');return x};
const quantity=v=>{const n=Number(v);if(!Number.isSafeInteger(n)||n<=0||n>1000000)throw Error('Adet pozitif tam sayı olmalı.');return n};
const vat=(input,rate,included)=>{const c=nonnegative(input),r=Number(rate);if(!Number.isFinite(r)||r<0||r>100)throw Error('KDV oranı 0-100 arasında olmalı.');const net=included?Math.round(c*100/(100+r)):c,tax=included?c-net:Math.round(c*r/100);return {netCents:net,vatCents:tax,grossCents:net+tax,rate:r}};
const day=date=>{const d=new Date(date);if(!Number.isFinite(d.getTime()))return '';const p=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:'Europe/Istanbul',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(d).map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}`};
const isoDate=v=>/^\d{4}-\d{2}-\d{2}$/.test(String(v))&&!Number.isNaN(Date.parse(v+'T12:00:00Z'))?String(v):'';
const name=o=>String(o?.customer?.fullName||o?.customer?.name||'—');
const lineName=x=>String(x?.product?.name||x?.name||'Ürün');
const key=x=>String(x?.product?.id||x?.productId||x?.product?.internalCode||'');
const orderItems=o=>Array.isArray(o.items)?o.items:[];
const hasPersonal=o=>orderItems(o).some(x=>x.personalized||(x.writes||x.setCustomization?.writes||[]).some(w=>String(w.text||'').trim())||(x.photoCustomizations||x.setCustomization?.photoCustomizations||[]).length>0);
const qline=x=>Math.max(1,Math.round(Number(x?.qty||1)));
function tariffMatches(t,order){const price=cents(order.total||0);return (!t.company||t.company===String(order.cargoCompany||''))&&price>=t.minCents&&(t.maxCents===null||price<=t.maxCents)&&(!t.startsOn||day(order.createdAt)>=t.startsOn)&&(!t.endsOn||day(order.createdAt)<=t.endsOn)}
function financeOrder(o,s){const id=String(o.id),c=s.costs[id]||{},refs=s.refunds.filter(x=>x.orderId===id),total=nonnegative(o.total||0),returned=refs.reduce((a,x)=>a+x.amountCents,0),netRevenue=Math.max(0,total-returned),recognized=(c.recognized===true||(c.recognized!==false&&o.status==='delivered'))&&o.status!=='cancelled';
  const allocations=s.allocations.filter(x=>x.orderId===id),lineCosts=[],issues=[];
  for(const [i,x] of orderItems(o).entries()){
    const qty=qline(x),alloc=allocations.filter(a=>a.lineIndex===i),allocatedQty=alloc.reduce((a,b)=>a+b.quantity,0),explicit=c.lines?.[i];
    const cost=alloc.length&&allocatedQty===qty?alloc.reduce((a,b)=>a+b.quantity*b.unitCostCents,0):Number.isSafeInteger(explicit?.unitCostCents)?explicit.unitCostCents*qty:null;
    if(cost===null)issues.push(`Ürün maliyeti eksik: ${lineName(x)}`);
    const resaleQty=refs.flatMap(r=>r.items||[]).filter(z=>z.lineIndex===i&&z.resellable).reduce((a,z)=>a+z.quantity,0),returnedQty=refs.flatMap(r=>r.items||[]).filter(z=>z.lineIndex===i).reduce((a,z)=>a+z.quantity,0);const linePrice=Number(x.product?.price??x.price??0)*qty+((x.writes||x.setCustomization?.writes||[]).reduce((n,w)=>n+Number(w.fee||0),0))+((x.photoCustomizations||x.setCustomization?.photoCustomizations||[]).reduce((n,p)=>n+Number(p.fee||0),0));
    lineCosts.push({lineIndex:i,productId:key(x),name:lineName(x),quantity:qty,costCents:cost,cogsCents:cost===null?null:Math.round(cost*(qty-Math.min(qty,resaleQty))/qty),returnedResellable:resaleQty,returnedQuantity:returnedQty,salesWeightCents:Math.max(0,cents(linePrice)),invoiceAllocated:allocatedQty});
  }
  const firstDay=day(o.createdAt),t=s.tariffs.find(t=>Date.parse(t.createdAt)<=Date.parse(o.createdAt)&&tariffMatches(t,{...o,cargoCompany:c.cargoCompany||'Aras Kargo / YeşilKar'}));let shipping=c.shippingActualCents??c.shippingEstimatedCents??t?.costCents??null;
  if(shipping===null)issues.push('Gidiş kargosu maliyeti eksik');
  const prs=s.personalizationRates.filter(r=>Date.parse(r.createdAt)<=Date.parse(o.createdAt)&&(!r.startsOn||r.startsOn<=firstDay)).sort((a,b)=>String(b.startsOn).localeCompare(String(a.startsOn)));
  const writing=orderItems(o).reduce((n,x)=>n+(x.writes||x.setCustomization?.writes||[]).filter(w=>String(w.text||'').trim()).length,0);
  const photos=orderItems(o).reduce((n,x)=>n+(x.photoCustomizations||x.setCustomization?.photoCustomizations||[]).length,0);
  const rateFor=type=>prs.find(p=>String(p.type||'').toLocaleLowerCase('tr-TR').includes(type))?.costCents??null;
  const writingRate=writing?rateFor('yaz'):0,photoRate=photos?rateFor('foto'):0,unclassifiedPersonal=hasPersonal(o)&&!writing&&!photos;
  const personalization=c.personalizationActualCents??(writingRate===null||photoRate===null||unclassifiedPersonal?null:writing*writingRate+photos*photoRate);
  if(personalization===null)issues.push('Kişiselleştirme maliyeti eksik');
  const other=s.expenses.filter(x=>x.orderId===id&&!x.voided).reduce((n,x)=>n+x.amountCents,0);
  const refundsLoss=refs.reduce((n,r)=>n+r.returnShippingCents+r.extraLossCents,0);
  // Damaged item cost remains in COGS: never count it a second time as a refund loss.
  const itemCost=lineCosts.some(x=>x.cogsCents===null)?null:lineCosts.reduce((n,x)=>n+x.cogsCents,0);
  const known=itemCost!==null&&shipping!==null&&personalization!==null;
  const profit=known?netRevenue-itemCost-shipping-personalization-other-refundsLoss:null;
  return {orderId:id,customer:name(o),date:firstDay,status:o.status||'new',recognized,hasPersonal:hasPersonal(o),totalCents:total,refundCents:returned,netRevenueCents:recognized?netRevenue:0,pendingRevenueCents:!recognized?netRevenue:0,profitCents:recognized?profit:null,estimatedProfitCents:!recognized?profit:null,costCents:itemCost,shippingCents:shipping,shippingEstimatedCents:c.shippingEstimatedCents??t?.costCents??null,personalizationCents:personalization,otherExpensesCents:other,returnLossCents:refundsLoss,issues,lines:lineCosts,salesInvoiced:!!c.salesInvoiced,outputVatRate:c.outputVatRate??null,outputVatIncluded:c.outputVatIncluded!==false,cargoCompany:c.cargoCompany||'',rawStatus:o.status||'new'};
}
function summarize(rows,expenses){const gross=rows.reduce((n,x)=>n+x.netRevenueCents,0),known=rows.filter(x=>x.recognized&&x.profitCents!==null),unknown=rows.filter(x=>x.recognized&&x.profitCents===null),profit=unknown.length?null:known.reduce((n,x)=>n+x.profitCents,0),general=expenses.filter(x=>!x.orderId&&!x.voided).reduce((n,x)=>n+x.amountCents,0);return {revenueCents:gross,profitCents:profit,operationalProfitCents:profit===null?null:profit-general,margin:profit!==null&&gross>0?Math.round(profit/gross*10000)/100:null,orders:rows.filter(x=>x.recognized).length,refundCents:rows.reduce((n,x)=>n+x.refundCents,0),returnLossCents:rows.reduce((n,x)=>n+x.returnLossCents,0),expensesCents:general+rows.reduce((n,x)=>n+x.otherExpensesCents+(x.shippingCents||0)+(x.personalizationCents||0)+x.returnLossCents,0),generalExpensesCents:general,unknownProfitOrders:unknown.length,pendingRevenueCents:rows.reduce((n,x)=>n+x.pendingRevenueCents,0)}}
function registerFinance(app,{readJson,writeJson,requireAdmin,sameOriginGuard,persist}){
 let running=Promise.resolve();const mutate=fn=>{const work=running.then(fn);running=work.catch(()=>{});return work};
 const read=()=>{const existing=readJson('finance_state.json',DEFAULT());return {...DEFAULT(),...existing}};
 const save=async s=>{writeJson('finance_state.json',s);await persist()};
 const audit=(s,kind,id,before,after)=>s.audit.push({id:crypto.randomUUID(),at:new Date().toISOString(),actor:'admin',kind,targetId:String(id),before,after});
 const ok=(res,data)=>res.set('Cache-Control','no-store').json({ok:true,...data});
 const err=(res,e)=>res.status(/(bulunam|yetersiz|çakış|stok|işlem)/i.test(e.message)?409:400).json({ok:false,message:e.message||'Finans kaydı yapılamadı.'});
 const guard=fn=>(req,res)=>mutate(async()=>{try{await fn(req,res)}catch(e){err(res,e)}}).catch(e=>{if(!res.headersSent)res.status(500).json({ok:false,message:'Finans verileri kalıcı olarak kaydedilemedi.'});console.error('finance',e)});
 const orders=()=>readJson('orders.json',[]);
 const requiredOrder=id=>{const o=orders().find(o=>String(o.id)===String(id));if(!o)throw Error('Sipariş bulunamadı.');return o};
 const reference=(s,id)=>s.purchases.flatMap(p=>p.lines.map(l=>({purchase:p,line:l}))).find(z=>z.line.id===id);
 const available=(s,id)=>{
  const ref=reference(s,id);if(!ref)return 0;
  // Tekrar satılabilir iadeler alış partisini fiziksel olarak serbest bırakır.
  // Önceki satışın maliyet snapshot'ı ve denetim kaydı korunur.
  const groups=new Map();for(const a of s.allocations){const k=a.orderId+':'+a.lineIndex;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(a)}
  let used=0;
  for(const [k,parts] of groups){const [orderId,lineIndex]=k.split(':'),returned=s.refunds.filter(x=>x.orderId===orderId).flatMap(x=>x.items||[]).filter(x=>x.resellable&&x.lineIndex===Number(lineIndex)).reduce((n,x)=>n+x.quantity,0);let reusable=returned;
    for(const a of parts){const free=Math.min(reusable,a.quantity);reusable-=free;if(a.batchId===id)used+=a.quantity-free;}}
  return ref.line.quantity-used;
 };
 const catalog=()=>readJson('catalog.json',{products:[]}).products||[];
 const report=(s,from,to)=>{const all=orders().map(o=>financeOrder(o,s)),selected=all.filter(o=>o.date>=from&&o.date<=to),expenses=s.expenses.filter(x=>x.date>=from&&x.date<=to),tot=summarize(selected,expenses),daily=new Map(),product=new Map(),categories=new Map();
   for(const o of selected){let r=daily.get(o.date)||{date:o.date,revenueCents:0,profitCents:0,orders:0,profitKnown:true};r.revenueCents+=o.netRevenueCents;r.profitCents+=o.profitCents||0;r.orders+=Number(o.recognized);if(o.recognized&&o.profitCents===null)r.profitKnown=false;daily.set(o.date,r);if(!o.recognized)continue;for(const x of o.lines){const p=product.get(x.productId)||{productId:x.productId,name:x.name,quantity:0,costCents:0,revenueCents:0,profitCents:0,missing:false,returns:0};const weight=o.lines.reduce((n,l)=>n+l.salesWeightCents,0),share=weight>0?x.salesWeightCents/weight:x.quantity/(o.lines.reduce((n,l)=>n+l.quantity,0)||1),val=Math.round(o.netRevenueCents*share);p.quantity+=x.quantity;p.revenueCents+=val;p.returns+=x.returnedQuantity;if(x.cogsCents===null)p.missing=true;else p.costCents+=x.cogsCents;p.profitCents+=val-(x.cogsCents||0)-Math.round(((o.shippingCents||0)+(o.personalizationCents||0)+o.otherExpensesCents+o.returnLossCents)*share);product.set(x.productId,p)}}
   for(const e of expenses.filter(x=>!x.voided))categories.set(e.category,(categories.get(e.category)||0)+e.amountCents);
   for(const o of selected.filter(x=>x.recognized))for(const [category,amountCents] of [['cargo',o.shippingCents||0],['personalization',o.personalizationCents||0],['return',o.returnLossCents]])if(amountCents)categories.set(category,(categories.get(category)||0)+amountCents);
   const stocks=s.purchases.flatMap(p=>p.lines.map(l=>({id:l.id,invoice:p.invoice,productId:l.productId,sku:l.sku,name:l.name,quantity:l.quantity,used:l.quantity-available(s,l.id),remaining:available(s,l.id),unitCostCents:l.unitCostCents,date:p.date})));return {totals:tot,orders:selected,trend:[...daily.values()].sort((a,b)=>a.date.localeCompare(b.date)),products:[...product.values()].sort((a,b)=>b.revenueCents-a.revenueCents),expenseCategories:[...categories.entries()].map(([category,amountCents])=>({category,amountCents})),stock:stocks,alerts:selected.filter(x=>x.issues.length).map(x=>({id:x.orderId,message:x.issues.join('; ')}))}}
 app.get('/api/admin/finance/report',requireAdmin,(req,res)=>{try{const from=isoDate(req.query.from)||'2000-01-01',to=isoDate(req.query.to)||'2999-12-31';if(from>to)throw Error('Tarih aralığı ters olamaz.');const s=read(),data=report(s,from,to),today=day(new Date()),month=today.slice(0,7),quick={today:summarize(report(s,today,today).orders,s.expenses.filter(x=>x.date===today)),month:summarize(report(s,month+'-01',month+'-31').orders,s.expenses.filter(x=>x.date.startsWith(month)))};const search=String(req.query.search||'').trim().toLocaleLowerCase('tr-TR'),page=Math.max(1,Math.floor(Number(req.query.page)||1)),filtered=search?data.orders.filter(x=>[x.orderId,x.customer,x.status].some(v=>String(v).toLocaleLowerCase('tr-TR').includes(search))):data.orders,limit=50,writingStats={all:data.orders.filter(x=>x.recognized).length,writes:data.orders.filter(x=>x.recognized&&x.hasPersonal).length};ok(res,{...data,orders:filtered.slice((page-1)*limit,page*limit),pagination:{page,pages:Math.ceil(filtered.length/limit),total:filtered.length},writingStats,quick,purchases:s.purchases,allocations:s.allocations,expenses:s.expenses.filter(x=>x.date>=from&&x.date<=to),refunds:s.refunds.filter(x=>x.date>=from&&x.date<=to),tariffs:s.tariffs,personalizationRates:s.personalizationRates,adjustments:s.vatAdjustments,productsCatalog:catalog().map(x=>({id:x.id,name:x.name,sku:x.internalCode||''}))})}catch(e){err(res,e)}});
 app.get('/api/admin/finance/order/:id',requireAdmin,(req,res)=>{try{const s=read(),o=requiredOrder(req.params.id),c=s.costs[String(o.id)]||{};ok(res,{order:financeOrder(o,s),source:{id:o.id,items:orderItems(o).map((x,i)=>({lineIndex:i,name:lineName(x),productId:key(x),qty:qline(x)}))},costs:c,allocations:s.allocations.filter(x=>x.orderId===String(o.id)),batches:s.purchases.flatMap(p=>p.lines.map(l=>({...l,purchaseDate:p.date,invoice:p.invoice,available:available(s,l.id)}))),refunds:s.refunds.filter(x=>x.orderId===String(o.id)),audit:s.audit.filter(x=>x.targetId===String(o.id)).slice(-50)})}catch(e){err(res,e)}});
 app.post('/api/admin/finance/order/:id/costs',requireAdmin,sameOriginGuard,guard(async(req,res)=>{const o=requiredOrder(req.params.id),s=read(),id=String(o.id),before=s.costs[id]||{},b=req.body||{};const c={...before};for(const fld of ['shippingEstimated','shippingActual','personalizationActual'])if(Object.hasOwn(b,fld))c[fld+'Cents']=b[fld]===''||b[fld]===null?null:nonnegative(b[fld],fld);if('recognized'in b){if(b.recognized===null)delete c.recognized;else c.recognized=!!b.recognized;}if('salesInvoiced'in b)c.salesInvoiced=!!b.salesInvoiced;if('outputVatRate'in b){const r=Number(b.outputVatRate);if(!Number.isFinite(r)||r<0||r>100)throw Error('Satış KDV oranı hatalı.');c.outputVatRate=r}if('outputVatIncluded'in b)c.outputVatIncluded=!!b.outputVatIncluded;if('cargoCompany'in b)c.cargoCompany=String(b.cargoCompany||'').slice(0,90);if('lines'in b){if(!Array.isArray(b.lines)||b.lines.length!==orderItems(o).length)throw Error('Ürün maliyet satırları uyuşmuyor.');c.lines=b.lines.map((x,i)=>({lineIndex:i,unitCostCents:x.unitCost===null||x.unitCost===''?null:nonnegative(x.unitCost)}))}if(c.salesInvoiced&&c.outputVatRate===undefined)throw Error('Satış faturası için KDV oranını girin (KDV yoksa 0).');if(c.salesInvoiced&&orderItems(o).some((x,i)=>s.allocations.filter(a=>a.orderId===id&&a.lineIndex===i).reduce((n,a)=>n+a.quantity,0)!==qline(x)))throw Error('Faturalı satış için ürünlerin faturalı stok partilerinden kullanımını tamamlayın.');s.costs[id]=c;audit(s,'order_cost',id,before,c);await save(s);ok(res,{order:financeOrder(o,s)})}));
 app.post('/api/admin/finance/purchases',requireAdmin,sameOriginGuard,guard(async(req,res)=>{const b=req.body||{},s=read(),date=isoDate(b.date),invoice=String(b.invoice||'').trim(),supplier=String(b.supplier||'').trim();if(!date||!invoice||!supplier||!Array.isArray(b.lines)||!b.lines.length)throw Error('Tarih, fatura numarası, tedarikçi ve ürünler zorunlu.');if(b.operationId){const old=s.operations.find(x=>x.key===b.operationId&&x.kind==='purchase');if(old)return ok(res,{purchase:s.purchases.find(x=>x.id===old.rowId)})}if(s.purchases.some(x=>x.invoice===invoice&&x.supplier===supplier))throw Error('Aynı tedarikçiye ait fatura zaten ekli.');const lines=b.lines.map(l=>{const productId=String(l.productId||'').trim(),p=catalog().find(x=>String(x.id)===productId||String(x.internalCode||'')===productId);if(!p)throw Error('Ürün eşleşmedi. Katalogdan geçerli ürün seçin.');const v=vat(l.price,l.vatRate??0,l.vatIncluded!==false);return {id:crypto.randomUUID(),productId:String(p.id),sku:String(p.internalCode||''),name:String(p.name),quantity:quantity(l.quantity),unitCostCents:v.netCents,unitGrossCents:v.grossCents,unitVatCents:v.vatCents,vatRate:v.rate,vatIncluded:l.vatIncluded!==false}});const oldOperation=s.operations.find(x=>x.key===b.operationId&&x.kind==='purchase');if(b.operationId&&oldOperation)return ok(res,{purchase:s.purchases.find(x=>x.id===oldOperation.rowId)});const row={id:crypto.randomUUID(),invoice,supplier,date,description:String(b.description||''),opening:!!b.opening,lines,createdAt:new Date().toISOString()};s.purchases.push(row);if(b.operationId)s.operations.push({kind:'purchase',key:b.operationId,rowId:row.id});audit(s,'purchase',row.id,null,row);await save(s);ok(res,{purchase:row})}));
 app.post('/api/admin/finance/allocate',requireAdmin,sameOriginGuard,guard(async(req,res)=>{const b=req.body||{},o=requiredOrder(b.orderId),lineIndex=Number(b.lineIndex),items=orderItems(o);if(!Number.isInteger(lineIndex)||!items[lineIndex])throw Error('Sipariş ürün satırı geçersiz.');const line=items[lineIndex],id=String(o.id),s=read(),parts=Array.isArray(b.parts)?b.parts:[];const fresh=parts.map(p=>({batchId:String(p.batchId||''),quantity:quantity(p.quantity)}));if(fresh.reduce((a,b)=>a+b.quantity,0)!==qline(line))throw Error('Dağıtılan toplam adet siparişteki adede eşit olmalı.');if(new Set(fresh.map(x=>x.batchId)).size!==fresh.length)throw Error('Aynı partiyi birden fazla kez seçmeyin.');for(const x of fresh){const batch=reference(s,x.batchId);if(!batch||batch.line.productId!==key(line))throw Error('Alış partisi bu sipariş ürünüyle eşleşmiyor.');const own=s.allocations.filter(a=>a.orderId===id&&a.lineIndex===lineIndex&&a.batchId===x.batchId).reduce((a,z)=>a+z.quantity,0);if(available(s,x.batchId)+own<x.quantity)throw Error('Bu ürün için kullanılabilir faturalı alış stoğu bulunmuyor.');x.unitCostCents=batch.line.unitCostCents;x.productId=batch.line.productId;x.lineIndex=lineIndex;x.orderId=id}
 const before=s.allocations.filter(a=>a.orderId===id&&a.lineIndex===lineIndex);if(before.length&&JSON.stringify(before.map(x=>[x.batchId,x.quantity]))===JSON.stringify(fresh.map(x=>[x.batchId,x.quantity]))){return ok(res,{allocations:before,order:financeOrder(o,s)})}s.allocations=s.allocations.filter(a=>a.orderId!==id||a.lineIndex!==lineIndex);s.allocations.push(...fresh);audit(s,'allocation',id,before,fresh);await save(s);ok(res,{allocations:fresh,order:financeOrder(o,s)})}));
 app.post('/api/admin/finance/allocate/undo',requireAdmin,sameOriginGuard,guard(async(req,res)=>{const o=requiredOrder(req.body?.orderId),lineIndex=Number(req.body?.lineIndex),s=read();const before=s.allocations.filter(x=>x.orderId===String(o.id)&&x.lineIndex===lineIndex);if(!before.length)throw Error('Geri alınacak faturalı stok kullanımı bulunmuyor.');s.allocations=s.allocations.filter(x=>x.orderId!==String(o.id)||x.lineIndex!==lineIndex);audit(s,'allocation_undo',String(o.id),before,null);await save(s);ok(res,{order:financeOrder(o,s)})}));
 app.post('/api/admin/finance/expenses',requireAdmin,sameOriginGuard,guard(async(req,res)=>{const b=req.body||{},s=read(),date=isoDate(b.date),amountCents=nonnegative(b.amount),category=String(b.category||'other');if(!date||amountCents<=0)throw Error('Tarih ve pozitif gider gerekli.');if(!['cargo','personalization','return','packaging','advertising','commission','other'].includes(category))throw Error('Gider kategorisi geçersiz.');if(b.orderId)requiredOrder(b.orderId);const oldOperation=s.operations.find(x=>x.key===b.operationId&&x.kind==='expense');if(b.operationId&&oldOperation)return ok(res,{expense:s.expenses.find(x=>x.id===oldOperation.rowId)});const row={id:crypto.randomUUID(),date,amountCents,category,orderId:String(b.orderId||''),note:String(b.note||'').slice(0,500),createdAt:new Date().toISOString(),voided:false};s.expenses.push(row);if(b.operationId)s.operations.push({kind:'expense',key:b.operationId,rowId:row.id});audit(s,'expense',row.id,null,row);await save(s);ok(res,{expense:row})}));
 app.post('/api/admin/finance/expenses/:id/void',requireAdmin,sameOriginGuard,guard(async(req,res)=>{if(req.body?.confirm!==true)throw Error('Gider iptali onaylanmalı.');const s=read(),x=s.expenses.find(x=>x.id===req.params.id);if(!x)throw Error('Gider bulunamadı.');if(x.voided)throw Error('Gider zaten iptal edildi.');x.voided=true;x.voidedAt=new Date().toISOString();audit(s,'expense_void',x.id,{voided:false},{voided:true});await save(s);ok(res,{expense:x})}));
 app.post('/api/admin/finance/refunds',requireAdmin,sameOriginGuard,guard(async(req,res)=>{const b=req.body||{},o=requiredOrder(b.orderId),s=read(),id=String(o.id),date=isoDate(b.date),amountCents=nonnegative(b.amount),returnShippingCents=nonnegative(b.returnShipping||0),extraLossCents=nonnegative(b.extraLoss||0);const oldOperation=s.operations.find(x=>x.key===b.operationId&&x.kind==='refund');if(b.operationId&&oldOperation)return ok(res,{refund:s.refunds.find(x=>x.id===oldOperation.rowId),order:financeOrder(o,s)});if(!date||amountCents===0)throw Error('İade tarihi ve tutarı gerekli.');const already=s.refunds.filter(x=>x.orderId===id).reduce((n,x)=>n+x.amountCents,0);if(already+amountCents>cents(o.total||0))throw Error('İade tutarı toplam satışı aşamaz.');const parts=(Array.isArray(b.items)?b.items:[]).map(x=>({lineIndex:Number(x.lineIndex),quantity:quantity(x.quantity),resellable:!!x.resellable}));if(new Set(parts.map(x=>x.lineIndex)).size!==parts.length)throw Error('İade için aynı ürün satırı iki kez girilemez.');for(const x of parts){const item=orderItems(o)[x.lineIndex];if(!item)throw Error('İade ürün satırı bulunamadı.');const count=s.refunds.filter(r=>r.orderId===id).flatMap(r=>r.items||[]).filter(t=>t.lineIndex===x.lineIndex).reduce((a,t)=>a+t.quantity,0);if(count+x.quantity>qline(item))throw Error('İade adedi satış adedini aşamaz.');}if(b.type==='full'&&already+amountCents!==cents(o.total||0))throw Error('Tam iade tutarı siparişin kalan tutarına eşit olmalı.');const row={id:crypto.randomUUID(),orderId:id,date,type:b.type==='full'?'full':'partial',amountCents,returnShippingCents,extraLossCents,items:parts,reason:String(b.reason||'').slice(0,500),createdAt:new Date().toISOString()};s.refunds.push(row);if(b.operationId)s.operations.push({kind:'refund',key:b.operationId,rowId:row.id});audit(s,'refund',id,null,row);await save(s);ok(res,{refund:row,order:financeOrder(o,s)})}));
 app.post('/api/admin/finance/tariffs',requireAdmin,sameOriginGuard,guard(async(req,res)=>{const b=req.body||{},s=read(),company=String(b.company||'').trim(),minCents=nonnegative(b.min||0),maxCents=b.max===''||b.max===null||b.max===undefined?null:nonnegative(b.max),costCents=nonnegative(b.cost),startsOn=isoDate(b.startsOn),endsOn=b.endsOn?isoDate(b.endsOn):null;if(!company||!startsOn||maxCents!==null&&maxCents<minCents||endsOn&&endsOn<startsOn)throw Error('Kargo tarifesi tarih veya aralığı hatalı.');const overlap=s.tariffs.filter(t=>t.company===company&&(!t.endsOn||t.endsOn>=startsOn)&&(!endsOn||t.startsOn<=endsOn));if(overlap.some(t=>(t.maxCents===null||t.maxCents>=minCents)&&(maxCents===null||t.minCents<=maxCents)))throw Error('Bu kargo şirketinin aynı tarihte çakışan ücret aralığı var.');const row={id:crypto.randomUUID(),company,minCents,maxCents,costCents,startsOn,endsOn,createdAt:new Date().toISOString()};s.tariffs.push(row);audit(s,'tariff',row.id,null,row);await save(s);ok(res,{tariff:row})}));
 app.post('/api/admin/finance/personalization',requireAdmin,sameOriginGuard,guard(async(req,res)=>{const b=req.body||{},s=read(),startsOn=isoDate(b.startsOn),costCents=nonnegative(b.cost);if(!startsOn||!String(b.type||'').trim())throw Error('Tür ve başlangıç tarihi gerekli.');const row={id:crypto.randomUUID(),type:String(b.type).trim().slice(0,120),startsOn,costCents,createdAt:new Date().toISOString()};s.personalizationRates.push(row);audit(s,'personalization',row.id,null,row);await save(s);ok(res,{rate:row})}));
 app.post('/api/admin/finance/vat-adjustment',requireAdmin,sameOriginGuard,guard(async(req,res)=>{const b=req.body||{},s=read(),period=String(b.period||'');if(!/^\d{4}-\d{2}$/.test(period))throw Error('Dönem YYYY-AA biçiminde olmalı.');const row={id:crypto.randomUUID(),period,amountCents:nonnegative(b.amount),note:String(b.note||''),createdAt:new Date().toISOString(),actor:'admin'};s.vatAdjustments.push(row);audit(s,'vat-adjustment',row.id,null,row);await save(s);ok(res,{adjustment:row})}));
 app.get('/api/admin/finance/vat',requireAdmin,(req,res)=>{try{const s=read(),period=String(req.query.period||day(new Date()).slice(0,7)),rows=orders().filter(o=>day(o.createdAt).startsWith(period)),purchases=s.purchases.filter(p=>p.date.startsWith(period)),purchaseVatCents=purchases.filter(p=>!p.opening).reduce((n,p)=>n+p.lines.reduce((a,l)=>a+l.quantity*l.unitVatCents,0),0),salesVatCents=rows.reduce((n,o)=>{const c=s.costs[String(o.id)];if(!c?.salesInvoiced||c?.outputVatRate===undefined||o.status==='cancelled')return n;const r=financeOrder(o,s),v=vat(money(r.netRevenueCents),c.outputVatRate,c.outputVatIncluded!==false);return n+v.vatCents},0);ok(res,{period,purchaseVatCents,salesVatCents,differenceCents:salesVatCents-purchaseVatCents,adjustments:s.vatAdjustments.filter(a=>a.period===period)})}catch(e){err(res,e)}});
 app.get('/api/admin/finance/export.xlsx',requireAdmin,(req,res)=>{try{const s=read(),from=isoDate(req.query.from)||'2000-01-01',to=isoDate(req.query.to)||'2999-12-31',data=report(s,from,to);const XLSX=require('xlsx'),wb=XLSX.utils.book_new(),rows=data.orders.map(x=>({'Sipariş':x.orderId,'Tarih':x.date,'Müşteri':x.customer,'Durum':x.status,'Gerçekleşti':x.recognized?'Evet':'Hayır','Net Ciro (TL)':money(x.netRevenueCents),'İade (TL)':money(x.refundCents),'Ürün Maliyeti (TL)':x.costCents===null?'Eksik':money(x.costCents),'Kargo (TL)':x.shippingCents===null?'Eksik':money(x.shippingCents),'Kişiselleştirme (TL)':x.personalizationCents===null?'Eksik':money(x.personalizationCents),'İade Zararı (TL)':money(x.returnLossCents),'Sipariş Kârı (TL)':x.profitCents===null?'Kesinleşmedi':money(x.profitCents)}));XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows.length?rows:[{'Bilgi':'Bu tarih aralığında kayıt yok'}]),'Sipariş Finans');const totals=data.totals;XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet([{'Net Ciro':money(totals.revenueCents),'Sipariş Kârı':totals.profitCents===null?'Kesinleşmedi':money(totals.profitCents),'Genel Gider':money(totals.generalExpensesCents),'Operasyonel Net Kâr':totals.operationalProfitCents===null?'Kesinleşmedi':money(totals.operationalProfitCents)}]),'Özet');res.set('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');res.set('Content-Disposition','attachment; filename="SHAZ-Finans.xlsx"');res.send(XLSX.write(wb,{type:'buffer',bookType:'xlsx'}))}catch(e){err(res,e)}});
}
module.exports={registerFinance,financeOrder,summarize,vat,cents,money,day,DEFAULT};
