'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const {registerFinance,financeOrder,DEFAULT}=require('../finance-service');
function build(){const routes={};const db={'orders.json':[ {id:'S1',createdAt:'2026-10-10T10:00:00+03:00',status:'new',total:1000,items:[{qty:2,product:{id:'watch',name:'Saat'}}]} ],'catalog.json':{products:[{id:'watch',name:'Saat'}]},'cargo_order_index.json':[{orderId:'S1',adminStage:'sent',stageUpdatedAt:'2026-10-11T10:00:00+03:00'}],'finance_state.json':DEFAULT()};const app={get:(u,...handlers)=>routes['GET '+u]=handlers.at(-1),post:(u,...handlers)=>routes['POST '+u]=handlers.at(-1)};registerFinance(app,{readJson:(n,def)=>structuredClone(db[n]??def),writeJson:(n,v)=>db[n]=structuredClone(v),requireAdmin:()=>{},sameOriginGuard:()=>{},persist:async()=>{}});async function call(method,url,body={},query={}){const handler=routes[method+' '+url];assert.ok(handler,`missing ${method} ${url}`);const res={statusCode:200,headersSent:false,set(){return this},status(n){this.statusCode=n;return this},json(v){this.headersSent=true;this.value=v;return this},send(v){this.headersSent=true;this.value=v;return this}};await handler({params:{id:body.pathId,type:body.pathType},body,query},res);return res}return {db,call}}
test('Gönderilenler finans satış listesinde görünür ama ciroya eklenmez; yeni sipariş görünmez',async()=>{const h=build();let r=(await h.call('GET','/api/admin/finance/report',{}, {from:'2026-10-01',to:'2026-10-31'})).value;assert.equal(r.orders.length,1);assert.equal(r.orders[0].status,'sent');assert.equal(r.totals.revenueCents,0);h.db['cargo_order_index.json'][0].adminStage='new';r=(await h.call('GET','/api/admin/finance/report',{}, {from:'2026-10-01',to:'2026-10-31'})).value;assert.equal(r.orders.length,0)});
test('Teslim edilince ciro olur; kargodan iade dönünce sıfırlanır, ikinci iade oluşturulmaz',async()=>{const h=build();const stage=h.db['cargo_order_index.json'][0];stage.adminStage='delivered';let r=(await h.call('GET','/api/admin/finance/report',{}, {from:'2026-10-01',to:'2026-10-31'})).value;assert.equal(r.totals.revenueCents,100000);stage.adminStage='returned';r=(await h.call('GET','/api/admin/finance/report',{}, {from:'2026-10-01',to:'2026-10-31'})).value;assert.equal(r.totals.revenueCents,0);assert.equal(r.refunds.length,1);assert.equal(r.refunds[0].automatic,true);assert.equal(h.db['finance_state.json'].refunds.length,0)});
test('Faturalı ve faturasız stok maliyeti otomatik kullanılır, faturalı stok dokunulmaz',async()=>{const h=build();let r=await h.call('POST','/api/admin/finance/purchases',{date:'2026-10-01',invoice:'FAT-1',supplier:'S',invoiced:true,lines:[{productId:'watch',quantity:1,price:190,vatRate:20,vatIncluded:false}]});assert.equal(r.statusCode,200);r=await h.call('POST','/api/admin/finance/purchases',{date:'2026-10-02',invoice:'GEN-1',supplier:'S',invoiced:false,lines:[{productId:'watch',quantity:1,price:220,vatRate:0,vatIncluded:true}]});assert.equal(r.statusCode,200);const data=(await h.call('GET','/api/admin/finance/report',{}, {from:'2026-10-01',to:'2026-10-31'})).value;assert.equal(data.orders[0].costCents,41000);assert.equal(data.stock.find(x=>x.invoiced).remaining,1);assert.equal(data.stock.find(x=>!x.invoiced).remaining,null);assert.equal(data.orders[0].issues.some(x=>x.includes('Ürün maliyeti')),false)});
test('Eski sipariş maliyeti sonraki alış fiyatları ile değişmez',async()=>{const h=build();await h.call('POST','/api/admin/finance/purchases',{date:'2026-10-01',invoice:'F1',supplier:'A',invoiced:false,lines:[{productId:'watch',quantity:2,price:200,vatRate:0}]});let r=(await h.call('GET','/api/admin/finance/report',{}, {from:'2026-10-01',to:'2026-10-31'})).value;assert.equal(r.orders[0].costCents,40000);await h.call('POST','/api/admin/finance/purchases',{date:'2026-10-01',invoice:'F2',supplier:'A',invoiced:false,lines:[{productId:'watch',quantity:5,price:999,vatRate:0}]});r=(await h.call('GET','/api/admin/finance/report',{}, {from:'2026-10-01',to:'2026-10-31'})).value;assert.equal(r.orders[0].costCents,40000)});
test('Silme denetim geçmişine yazar; maliyette kullanılan alış partisi silinemez',async()=>{const h=build();const r=await h.call('POST','/api/admin/finance/purchases',{date:'2026-10-01',invoice:'F1',supplier:'A',invoiced:true,lines:[{productId:'watch',quantity:2,price:200,vatRate:0}]});const id=r.value.purchase.id;const denied=await h.call('POST','/api/admin/finance/remove/:type/:id',{pathId:id,pathType:'purchase',confirm:true});assert.equal(denied.statusCode,409);assert.match(denied.value.message,/silinemez/)});
test('Şifre sıfırlama arayüzü mesajlı ve tek tık; giriş e-posta / telefon destekli',()=>{const app=fs.readFileSync(path.join(__dirname,'../public/app.js'),'utf8'),server=fs.readFileSync(path.join(__dirname,'../server.js'),'utf8');assert.match(app,/if\(btn.disabled\)return;const identifier/);assert.match(app,/BAĞLANTI GÖNDERİLDİ/);assert.match(server,/const previousUser=\{\.\.\.users\[i\]\}/);assert.match(server,/x\.email===email\|\|\(phone&&normalizeAccountPhone\(x\.phone\)===phone\)/)});
